name = "triple"
compatibility_date = "2026-09-15"
pages_build_output_dir = "dist"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "3room-media"

[vars]
R2_PUBLIC_BASE_URL = "https://pub-776d8a270e67409bb1704e375af76a79.r2.dev"
